import type { 
  Conversation,
  CreateConversation,
  UpdateConversationDetails,
  AssignConversation,
  UpdateConversationStatus,
  UpdateConversationPriority,
  RateConversation,
  ArchiveConversation,
  DeleteConversation,
  ConversationFilters,
  CloseConversation,
  ResolveConversation,
  SearchConversation,
  ListConversation,
  LockConversation,
  ReopenConversation,
  TransferConversation,
  MergeConversation,
  RestoreConversation,
} from "../schemas/conversation.schema.js";

export type {
  Conversation,
  CreateConversation,
  UpdateConversationDetails,
  AssignConversation,
  UpdateConversationStatus,
  UpdateConversationPriority,
  RateConversation,
  ArchiveConversation,
  DeleteConversation,
  ConversationFilters,
  CloseConversation,
  ResolveConversation,
  SearchConversation,
  ListConversation,
  LockConversation,
  ReopenConversation,
  TransferConversation,
  MergeConversation,
  RestoreConversation,
}
