/*
  Warnings:

  - The values [CREATED,ASSIGNED,UNASSIGNED,STATUS_CHANGED,PRIORITY_CHANGED,CUSTOMER_RATED,CLOSED,REOPENED,LOCKED,UNLOCKED,RESOLVED] on the enum `ConversationEventType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ConversationEventType_new" AS ENUM ('CONVERSATION_CREATED', 'CONVERSATION_ASSIGNED', 'CONVERSATION_UNASSIGNED', 'CONVERSATION_STATUS_CHANGED', 'CONVERSATION_PRIORITY_CHANGED', 'CONVERSATION_LOCKED', 'CONVERSATION_UNLOCKED', 'CONVERSATION_RESOLVED', 'CONVERSATION_CLOSED', 'CONVERSATION_REOPENED', 'CONVERSATION_RATED', 'TAG_ADDED', 'TAG_REMOVED', 'PARTICIPANT_ADDED', 'PARTICIPANT_REMOVED', 'MESSAGE_SENT', 'MESSAGE_EDITED', 'MESSAGE_DELETED', 'MESSAGE_READ', 'INTERNAL_NOTE_CREATED');
ALTER TABLE "ConversationEvent" ALTER COLUMN "type" TYPE "ConversationEventType_new" USING ("type"::text::"ConversationEventType_new");
ALTER TYPE "ConversationEventType" RENAME TO "ConversationEventType_old";
ALTER TYPE "ConversationEventType_new" RENAME TO "ConversationEventType";
DROP TYPE "public"."ConversationEventType_old";
COMMIT;
