export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",

  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",

  CREATE_ORDER = "CREATE_ORDER",
  UPDATE_ORDER = "UPDATE_ORDER",
  CANCEL_ORDER = "CANCEL_ORDER",

  INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT",

  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",

  ROLE_UPDATED = "ROLE_UPDATED",
}