-- CreateEnum
CREATE TYPE "SupportTeamEventType" AS ENUM ('MEMBER_ADDED', 'MEMBER_REMOVED', 'MEMBER_ROLE_CHANGED', 'MEMBER_ACTIVATED', 'MEMBER_DEACTIVATED', 'TEAM_CREATED', 'TEAM_UPDATED', 'TEAM_ACTIVATED', 'TEAM_DEACTIVATED');
